apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphwise-graph-automation-morphkgc.fullname" . }}
  namespace: {{ include "graphwise-graph-automation-morphkgc.namespace" . }}
  labels:
    {{- include "graphwise-graph-automation-morphkgc.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.configuration.properties -}}
    {{- range $key, $value := .Values.configuration.properties -}}
      {{- if ne $value nil -}}
        {{- printf "%s: %s" $key (tpl ($value | toString) $ | quote) | nindent 2 -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
