{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "graphwise-graph-automation-morphkgc.fullname" . }}
  namespace: {{ include "graphwise-graph-automation-morphkgc.namespace" . }}
  labels:
    {{- include "graphwise-graph-automation-morphkgc.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graphwise-graph-automation-morphkgc.selectorLabels" . | nindent 6 }}
{{- end }}
